services:
  dashboard:
    container_name: sysadm-dashboard
    user: "${UID}:${GID}"
    build: .
    image: sysadm-dashboard
    network_mode: host
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logging.kdev:5515"
        syslog-format: rfc5424
        tag: "docker_sysadm-dashboard"
        syslog-facility: "daemon"
    # Not needed when using network_mode: host
    # ports:
    #   - "0.0.0.0:${DASHBOARD_PORT:-5000}:5000"
    volumes:
      # Mapping host filesystem to container filesystem
      - ${STATUS_FILES_PATH}:/data/status
      - ${RELEASE_FILES_PATH}:/data/releases
      - ${DATABASE_FILES_PATH}:/data/db
    environment:
      - FLASK_PORT=${DASHBOARD_PORT}
      - STATUS_DIR=/data/status
      - RELEASE_DIR=/data/releases
      - DATABASE_FILE=/data/db/dashboard.db
      - TZ=${TIMEZONE}
    restart: unless-stopped
