services:
  dashboard:
    container_name: ansible-dashboard
    build: .
    image: ansible-dashboard
    network_mode: host
    # Not needed when using network_mode: host
    # ports:
    #   - "0.0.0.0:${DASHBOARD_PORT:-5000}:5000"
    volumes:
      - ${STATUS_FILES_PATH:-/var/log/ansible/status}:/data/status
    environment:
      - FLASK_PORT=${DASHBOARD_PORT:-5000}
      - STATUS_DIR=/data/status
      - TZ=${TIMEZONE:-Europe/Amsterdam}
    restart: unless-stopped
